[project]
name = "integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faker>=30.8.0",
    "httpx>=0.27.2",
    "pytest>=8.3.3",
]
